### ISSUE TITLE
Na konci czech-full.md je netisknutelný znak

### ISSUE THREAD

**Issue by ah01** [maly/edushield#3]
Na konci generovaného souboru [czech-full.md](https://github.com/maly/edushield/blob/master/extras/learning/course/cz/czech-full.md) je netisknutelný znak `SUB` (0x1A)

Viz http://stackoverflow.com/questions/9699976/batch-script-to-merge-files-without-hex-char-1a-at-the-end

--- 
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41651278-na-konci-czech-full-md-je-netisknutelny-znak?utm_campaign=plugin&utm_content=tracker%2F48017659&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F48017659&utm_medium=issues&utm_source=github).

**Comment by bechynsky** [comment]
Už by to mělo být v pořádku.
